### PR TITLE
Add lslidar_c16 ros2 driver early works.

### PR DESCRIPTION
**Pull request by ZhenshengLee**
Add lslidar_c16 ros2 driver early works.

### CODE REVIEW

**Comment by ZhenshengLee** [comment]
@tianb03 May you give this a simple review.

**Comment by ZhenshengLee** [comment]
You should create new branchs for melodic and foxy.

**Comment by tianb03** [comment]
Sorry Zhensheng this is not an official repo and I may not maintain this repo for general use... fork and maintain your repo will be ok.

**Comment by ZhenshengLee** [comment]
> Sorry Zhensheng this is not an official repo and I may not maintain this repo for general use... fork and maintain your repo will be ok.

OK.

**Pull request closed without merging**
